---
title: "EPI 590R Final Project"
author: "Kelly Longhini"
format:
  html:
    embed-resources: true
execute: 
  echo: false
---

```{r}
#| warning: false
#| message: false

# Install and call packages

install.packages("tidyverse")
install.packages("dplry")
install.packages("rmarkdown")
install.packages("gtsummary")
install.packages("here")
install.packages("broom")

library(tidyverse)
library(dplyr)
library(rmarkdown)
library(gtsummary)
library(here)
library(broom)
```

## Description of the data
The data comes from.....

```{r}
# Load in the catheterization R data set using the here package
load(here::here("data", "raw", "cath.rda")) 

cath <- cath %>%
  mutate(sex_cat = factor(cath$sex, labels = c("Male", "Female")))

```


## Table of descriptive statistics
```{r}
#| label: tbl-one
#| tbl-cap: "Table of descriptive statistics"

tbl_summary(
  cath,
  by = sex_cat,
  include = c(sex_cat, age, cad_dur, choleste),
  label = list(
    age ~ "Age (years)",
    cad_dur ~ "Duration of chest pain symptoms (days)",
    choleste ~ "Serum cholesterol level (milligrams per deciliter)"
  ),
  missing_text = "Missing") %>%
  add_overall(last = TRUE)
```

@tbl-one displays descriptive statistics for the predictor variables in the data set, including age, duration of chest pain symptoms, and serum cholesterol level. 



